package panels;

import transformacoes.SistemaSolar;

/**
 * Representa o menu para manipulação da circunferência
 *
 */
public class PanelMenuSistemaSolar extends javax.swing.JPanel {

    private static PanelMenuSistemaSolar instance;

    public static synchronized PanelMenuSistemaSolar getInstance() {
        if (instance == null) {
            instance = new PanelMenuSistemaSolar();
        }
        return instance;
    }

    /**
     * Construtor
     */
    private PanelMenuSistemaSolar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFiltros = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        btStop = new javax.swing.JButton();
        btRestart = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(240, 32767));
        setMinimumSize(new java.awt.Dimension(240, 0));
        setPreferredSize(new java.awt.Dimension(240, 779));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        btStop.setText("Parar Execução");
        btStop.setPreferredSize(new java.awt.Dimension(107, 30));
        btStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopAnimation(evt);
            }
        });

        btRestart.setText("Reiniciar Execução");
        btRestart.setEnabled(false);
        btRestart.setPreferredSize(new java.awt.Dimension(107, 30));
        btRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartAnimation(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRestart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRestart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(642, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stopAnimation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopAnimation
        SistemaSolar.threadAnimation.stop();
        btRestart.setEnabled(true);
    }//GEN-LAST:event_stopAnimation

    private void restartAnimation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartAnimation
        SistemaSolar sistemaSolar = new SistemaSolar();
        sistemaSolar.startAnimation();
        btRestart.setEnabled(false);
    }//GEN-LAST:event_restartAnimation


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRestart;
    private javax.swing.JButton btStop;
    private javax.swing.ButtonGroup buttonGroupFiltros;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
