package panels;

import javax.swing.JRadioButton;

import auxiliares.GraficosEnum;

/**
 * Representa o menu para manipulação da circunferÃªncia
 *
 */
public class PanelMenuGraficos extends javax.swing.JPanel {

    private static PanelMenuGraficos instance;
    private GraficosEnum tipoAlgoritimo;

    public static synchronized PanelMenuGraficos getInstance() {
        if (instance == null) {
            instance = new PanelMenuGraficos();
        }
        return instance;
    }

    /**
     * Construtor
     */
    private PanelMenuGraficos() {
        initComponents();
    }

    public void setTipoAlgoritimo(GraficosEnum tipoAlgoritimo) {
        this.tipoAlgoritimo = tipoAlgoritimo;
    }

    public GraficosEnum getTipoAlgoritimo() {
        if (rbColuna.isSelected()) {
            setTipoAlgoritimo(GraficosEnum.COLUNA);
        } else if (rbBarra.isSelected()) {
            setTipoAlgoritimo(GraficosEnum.BARRA);
        } else if (rbPie.isSelected()) {
            setTipoAlgoritimo(GraficosEnum.PIE);
        }

        return tipoAlgoritimo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFiltros = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        rbColuna = new javax.swing.JRadioButton();
        rbBarra = new javax.swing.JRadioButton();
        rbPie = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(240, 32767));
        setMinimumSize(new java.awt.Dimension(240, 0));
        setPreferredSize(new java.awt.Dimension(240, 779));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos de Gráicos"));

        buttonGroupFiltros.add(rbColuna);
        rbColuna.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbColuna.setSelected(true);
        rbColuna.setText("Coluna");
        rbColuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrosSelect(evt);
            }
        });

        buttonGroupFiltros.add(rbBarra);
        rbBarra.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbBarra.setText("Barra");
        rbBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrosSelect(evt);
            }
        });

        buttonGroupFiltros.add(rbPie);
        rbPie.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbPie.setText("Pizza (Pie)");
        rbPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrosSelect(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbColuna)
                    .addComponent(rbBarra)
                    .addComponent(rbPie))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbColuna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbBarra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbPie)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(643, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filtrosSelect(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrosSelect
        JRadioButton radio = (JRadioButton) evt.getSource();
        PanelFiltros.getInstance().setTitle("Filtro de " + radio.getText());
    }//GEN-LAST:event_filtrosSelect


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFiltros;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rbBarra;
    private javax.swing.JRadioButton rbColuna;
    private javax.swing.JRadioButton rbPie;
    // End of variables declaration//GEN-END:variables
}
